[workspace]
resolver = "2"
members = ["apps/*"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = "fat"
codegen-units = 1
opt-level = 'z'
strip = "symbols"
debug = false
overflow-checks = false
debug-assertions = false
