name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Minimal Linux build test
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check pwd
        run: pwd

      - name: List files
        run: ls -la

      - name: Show Cargo.toml
        run: cat Cargo.toml

      - name: Cargo version
        run: cargo --version

      - name: Rustc version
        run: rustc --version

      - name: Build hello
        run: cargo check -p hello

      - name: Build rustcam
        run: cargo check -p rustcam
